"""empty message

Revision ID: 61474f52bb9a
Revises: 0080bbe8decf
Create Date: 2023-02-07 16:44:17.593981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61474f52bb9a'
down_revision = '0080bbe8decf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_code',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('email_code')
    # ### end Alembic commands ###
